name: integration
on:
  pull_request:
  push:
    branches:
      - ft-capstone-apis
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
  unit-tests:
    runs-on: ubuntu-latest
    env:
      PORT: ${{secrets.PORT}}
      HOST: ${{secrets.HOST}}
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      SECRET: ${{secrets.SECRET}}
      NODE_ENV: ${{secrets.NODE_ENV}}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run test